# Generated by Django 3.2.18 on 2023-03-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.AddField(
            model_name='product',
            name='date_of_purchase',
            field=models.DateField(default='2023-04-23'),
            preserve_default=False,
        ),
    ]
