# Generated by Django 3.2.18 on 2023-03-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230327_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interested',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='interested',
            old_name='product_id',
            new_name='product',
        ),
    ]
