# Generated by Django 3.2.18 on 2023-03-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230327_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interested',
            unique_together={('product', 'buyer')},
        ),
    ]
